# Generated by Django 4.2.7 on 2023-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=3)),
                ('course', models.CharField(max_length=255)),
                ('music_instrumet', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('pay_or_not', models.CharField(max_length=255)),
            ],
        ),
    ]
