# Generated by Django 4.2.7 on 2023-11-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
